version: '2'

services:
    app:
        image: dockerphp/nginx:7.1-jessie
        volumes:
            - .:/app
            - /app/var/
            - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:443"
