export const FETCH_SURVEY_QUESTIONS = 'FETCH_SURVEY_QUESTIONS';
export const UPDATE_ANSWER_RESULT = 'UPDATE_ANSWER_RESULT';
export const UPDATE_CATEGORIES_VALUE = 'UPDATE_CATEGORIES_VALUE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const UPDATE_NB_QUESTIONS = 'UPDATE_NB_QUESTIONS';
